# Generated by Django 5.0.1 on 2024-12-24 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobFair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinator', models.CharField(max_length=200)),
                ('industry_focus', models.CharField(max_length=255)),
                ('number_of_companies', models.PositiveIntegerField()),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jobfair', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainer', models.CharField(max_length=200)),
                ('topic', models.CharField(max_length=255)),
                ('duration', models.DurationField()),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='podcast', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='Webinar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainer', models.CharField(max_length=200)),
                ('training_field', models.CharField(max_length=255)),
                ('capacity', models.PositiveIntegerField()),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='webinar', to='events.event')),
            ],
        ),
    ]
