# Generated by Django 5.0.1 on 2024-12-26 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClubMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('linkedin_link', models.URLField(blank=True, null=True)),
                ('pustcesf_link', models.URLField(blank=True, null=True)),
                ('role', models.CharField(choices=[('Founder', 'Founder'), ('Executive', 'Executive'), ('Advisor', 'Advisor'), ('Pre-Executive', 'Pre-Executive'), ('Club Designation', 'Club Designation')], max_length=20)),
                ('advisor_designation', models.CharField(blank=True, max_length=255, null=True)),
                ('advisor_department', models.CharField(blank=True, max_length=255, null=True)),
                ('founding_date', models.DateField(blank=True, null=True)),
                ('executive_work', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateField(blank=True, null=True)),
                ('is_visible_on_website', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Club Member',
                'verbose_name_plural': 'Club Members',
            },
        ),
    ]
