# Generated by Django 5.0.1 on 2024-12-26 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpanel', '0002_alter_clubmember_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubmember',
            name='role',
            field=models.CharField(choices=[('Founder', 'Founder'), ('Executive', 'Executive'), ('Pre-Executive', 'Pre-Executive'), ('Club Designation', 'Club Designation'), ('External Advisor', 'External Advisor'), ('Internal', 'Internal Advisor')], max_length=20),
        ),
    ]
