# Generated by Django 5.0.1 on 2024-12-21 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myport', '0002_profile_career_objective_profile_interests_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='volunteerexperience',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Achievement',
        ),
        migrations.DeleteModel(
            name='Certification',
        ),
        migrations.DeleteModel(
            name='Publication',
        ),
        migrations.DeleteModel(
            name='VolunteerExperience',
        ),
    ]
