# Generated by Django 5.0.1 on 2024-12-22 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myport', '0003_remove_certification_profile_and_more'),
        ('myport2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerexperience',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_experiences', to='myport.profile'),
        ),
    ]
